### ISSUE TITLE
How to set the log target?

### ISSUE THREAD

**Issue by apepkuss** [juntyr/wasi-logger#3]
Hi @juntyr,

How to set the log target, such as "stdout" or "stderr"? It would be better to provide an example in `README.md`. Thanks a lot!

**Comment by juntyr** [comment]
You can set the target as usual with `log`, e.g
```rust
info!(target: "stdout", "my message");
```
(see https://docs.rs/log/latest/log/#examples). On the host side, you would then need an implementation that checks if the target string matches the special-case `"stdout"` or `"stderr"` strings to deal with them appropriately.

**Comment by apepkuss** [comment]
Is there a way to set `target` like the way `env_logger` does? The following is an example picked from `env_logger`:

```rust
use std::env;
use env_logger::{Builder, Target};

let mut builder = Builder::from_default_env();
builder.target(Target::Stdout);  <=== this is a better way to set target value

builder.init();
```

**Comment by juntyr** [comment]
This crate doesn’t do any of the log outputting, it just translates log! Rust invocations into wasi:log calls on the WASM guest. You then still need another library on the host side which provides the wasi:log interface and e.g. translates them back into log! invocations. You would then need to set the target output on the host side. If you want to be able to modify it from the guest, you need a solution like the one I suggested where you encode the target somewhere in the log message information and then react to that on the host side.

**Comment by apepkuss** [comment]
Got it. Thanks a lot!
